worker_processes 1;
events { worker_connections 1024; }

http {
  upstream product_service  { server product-service:5001; }
  upstream order_service    { server order-service:5002; }
  upstream user_service     { server user-service:5003; }

  server {
    listen 80;

    # Servir el frontend
    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
    }

    # Redirigir /api/products -> product-service
    location /api/products/ {
      rewrite ^/api/products/(.*) /$1 break;
      proxy_pass http://product_service;
      proxy_set_header Host $host;
      add_header X-Proxied-By api-gateway;
    }

    # Redirigir /api/orders -> order-service
    location /api/orders/ {
      rewrite ^/api/orders/(.*) /$1 break;
      proxy_pass http://order_service;
      proxy_set_header Host $host;
      add_header X-Proxied-By api-gateway;
    }

    # Redirigir /api/users -> user-service
    location /api/users/ {
      rewrite ^/api/users/(.*) /$1 break;
      proxy_pass http://user_service;
      proxy_set_header Host $host;
      add_header X-Proxied-By api-gateway;
    }
  }
}